import type { Tag } from '@/typings';
import {
  mdiFruitPineapple,
  mdiGithub,
  mdiTailwind,
  mdiLanguagePhp,
  mdiLanguageGo,
  mdiLanguageTypescript,
  mdiGitlab,
  mdiGit,
  mdiVuejs,
  mdiLanguageCsharp,
  mdiMicrosoftWindows,
  mdiLanguageJava,
  mdiSymfony,
  mdiWordpress,
  mdiAngular,
  mdiLanguageCss3,
  mdiTestTube,
  mdiJira,
  mdiDatabaseSearch,
  mdiCodeBlockTags,
  mdiRocket,
  mdiQueueFirstInLastOut,
  mdiAlphabetLatin,
  mdiPageLayoutBody,
  mdiMicrosoftVisualStudioCode,
  mdiEslint,
  mdiBook
} from '@mdi/js';

export default {
  cypress : { label: "Cypress", svgIconPath: mdiTestTube },
  pinia : { label: "Pinia", svgIconPath: mdiFruitPineapple },
  gha : { label: "Github Actions", svgIconPath: mdiRocket },
  tailwind : { label: "Tailwind", svgIconPath: mdiTailwind },
  figma : { label: "Figma", svgIconPath: mdiPageLayoutBody },
  php : { label: "PHP", svgIconPath: mdiLanguagePhp },
  go : { label: "Go", svgIconPath: mdiLanguageGo },
  sql : { label: "SQL", svgIconPath: mdiDatabaseSearch },
  symfony : { label: "Symfony", svgIconPath: mdiSymfony },
  vue : { label: "Vue", svgIconPath: mdiVuejs },
  typescript : { label: "Typescript", svgIconPath: mdiLanguageTypescript },
  css : { label: "CSS", svgIconPath: mdiLanguageCss3 },
  unitTest : { label: "Unit tests", svgIconPath: mdiTestTube },
  e2eTest : { label: "e2e tests", svgIconPath: mdiTestTube },
  scrumEvents : { label: "Scrum events", svgIconPath: mdiJira },
  english : { label: "English", svgIconPath: mdiAlphabetLatin },
  german : { label: "German", svgIconPath: mdiAlphabetLatin },
  french : { label: "French", svgIconPath: mdiAlphabetLatin },
  gitlab : { label: "Gitlab", svgIconPath: mdiGitlab },
  git : { label: "Git", svgIconPath: mdiGit },
  jenkins : { label: "Jenkins", svgIconPath: mdiRocket },
  jest : { label: "Jest", svgIconPath: mdiTestTube },
  angular : { label: "Angular", svgIconPath: mdiAngular },
  github : { label: "Github", svgIconPath: mdiGithub },
  phpUnit : { label: "PHP Unit", svgIconPath: mdiTestTube },
  wordpress : { label: "Wordpress", svgIconPath: mdiWordpress },
  postgresql : { label: "PostgreSQL", svgIconPath: mdiDatabaseSearch },
  mysql : { label: "MySQL", svgIconPath: mdiDatabaseSearch },
  soap : { label: "SOAP", svgIconPath: mdiCodeBlockTags },
  java : { label: "Java", svgIconPath: mdiLanguageJava },
  redis : { label: "Redis", svgIconPath: mdiQueueFirstInLastOut },
  csharp : { label: "CSharp", svgIconPath: mdiLanguageCsharp },
  windowsForm : { label: "Windows form", svgIconPath: mdiMicrosoftWindows },
  vscode : { label: "VSCode", svgIconPath: mdiMicrosoftVisualStudioCode },
  eslint : { label: "esLint", svgIconPath: mdiEslint },
  storybook : { label: "Storybook", svgIconPath: mdiBook }
} as Record<string, Tag>;
