import type { Tag } from "@/typings";
import {
  mdiFruitPineapple,
  mdiGithub,
  mdiTailwind,
  mdiLanguagePhp,
  mdiLanguageGo,
  mdiLanguageTypescript,
  mdiGitlab,
  mdiGit,
  mdiVuejs,
  mdiLanguageCsharp,
  mdiMicrosoftWindows,
  mdiLanguageJava,
  mdiSymfony,
  mdiWordpress,
  mdiAngular,
  mdiLanguageCss3,
  mdiTestTube,
  mdiJira,
  mdiDatabaseSearch,
  mdiCodeBlockTags,
  mdiRocket,
  mdiQueueFirstInLastOut,
  mdiAlphabetLatin,
  mdiPageLayoutBody,
  mdiMicrosoftVisualStudioCode,
  mdiEslint,
  mdiBook,
  mdiAws,
  mdiKubernetes,
  mdiTerraform,
  mdiSpeedometer,
} from "@mdi/js";

export default {
  // Frontend
  cypress : { label: "Cypress", svgIconPath: mdiTestTube, category: "frontend" },
  playwright : { label: "Playwright", svgIconPath: mdiTestTube, category: "frontend" },
  tailwind : { label: "Tailwind", svgIconPath: mdiTailwind, category: "frontend" },
  vue : { label: "Vue", svgIconPath: mdiVuejs, category: "frontend" },
  nuxt : { label: "Nuxt", svgIconPath: mdiVuejs, category: "frontend" },
  typescript : { label: "Typescript", svgIconPath: mdiLanguageTypescript, category: "frontend" },
  vite : { label: "Vite", svgIconPath: mdiSpeedometer, category: "frontend" },
  css : { label: "CSS", svgIconPath: mdiLanguageCss3, category: "frontend" },
  angular : { label: "Angular", svgIconPath: mdiAngular, category: "frontend" },
  jest : { label: "Jest", svgIconPath: mdiTestTube, category: "frontend" },
  eslint : { label: "esLint", svgIconPath: mdiEslint, category: "frontend" },
  storybook : { label: "Storybook", svgIconPath: mdiBook, category: "frontend" },

  // Backend
  php : { label: "PHP", svgIconPath: mdiLanguagePhp, category: "backend" },
  go : { label: "Go", svgIconPath: mdiLanguageGo, category: "backend" },
  symfony : { label: "Symfony", svgIconPath: mdiSymfony, category: "backend" },
  java : { label: "Java", svgIconPath: mdiLanguageJava, category: "backend" },
  csharp : { label: "CSharp", svgIconPath: mdiLanguageCsharp, category: "backend" },
  soap : { label: "SOAP", svgIconPath: mdiCodeBlockTags, category: "backend" },
  phpUnit : { label: "PHP Unit", svgIconPath: mdiTestTube, category: "backend" },
  wordpress : { label: "Wordpress", svgIconPath: mdiWordpress, category: "backend" },

  // Database
  sql : { label: "SQL", svgIconPath: mdiDatabaseSearch, category: "database" },
  postgresql : { label: "PostgreSQL", svgIconPath: mdiDatabaseSearch, category: "database" },
  mysql : { label: "MySQL", svgIconPath: mdiDatabaseSearch, category: "database" },
  redis : { label: "Redis", svgIconPath: mdiQueueFirstInLastOut, category: "database" },

  // DevOps
  aws : { label: "AWS", svgIconPath: mdiAws, category: "devops" },
  kubernetes : { label: "Kubernetes", svgIconPath: mdiKubernetes, category: "devops" },
  terraform : { label: "Terraform", svgIconPath: mdiTerraform, category: "devops" },
  gha : { label: "Github Actions", svgIconPath: mdiRocket, category: "devops" },
  gitlab : { label: "Gitlab", svgIconPath: mdiGitlab, category: "devops" },
  git : { label: "Git", svgIconPath: mdiGit, category: "devops" },
  jenkins : { label: "Jenkins", svgIconPath: mdiRocket, category: "devops" },
  github : { label: "Github", svgIconPath: mdiGithub, category: "devops" },

  // Design
  figma : { label: "Figma", svgIconPath: mdiPageLayoutBody, category: "design" },

  // Other
  pinia : { label: "Pinia", svgIconPath: mdiFruitPineapple, category: "other" },
  unitTest : { label: "Unit tests", svgIconPath: mdiTestTube, category: "other" },
  e2eTest : { label: "e2e tests", svgIconPath: mdiTestTube, category: "other" },
  scrumEvents : { label: "Scrum events", svgIconPath: mdiJira, category: "other" },
  english : { label: "English", svgIconPath: mdiAlphabetLatin, category: "other" },
  german : { label: "German", svgIconPath: mdiAlphabetLatin, category: "other" },
  french : { label: "French", svgIconPath: mdiAlphabetLatin, category: "other" },
  windowsForm : { label: "Windows form", svgIconPath: mdiMicrosoftWindows, category: "other" },
  vscode : { label: "VSCode", svgIconPath: mdiMicrosoftVisualStudioCode, category: "other" },
} as Record<string, Tag>;
